In [2]:
import numpy as np

In [ ]:
arr1 = np.array([2,3,5,6,7,8])
print(arr1)

[2 3 5 6 7 8]


In [ ]:
arr1 = np.array([[2,3,4,5],[6,7,8,9]])
print(arr1)
np.zeros((6,3))
np.ones((2,2))
np.arange(1, 10, 2)
np.linspace(1, 10, 5)

[[2 3 4 5]
 [6 7 8 9]]


array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
arr1 = np.array([[[1,2,3,4],[5,6,7,8]],
 [[9,10,11,12],[13,14,15,33]]])
print(arr1)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 33]]]


In [ ]:
arr = np.array([[1,2,3],[4,5,6]])

print(arr.shape)   # (rows, columns)
print(arr.size)    # total elements
print(arr.ndim)    # number of dimensions
print(arr.dtype)   # data type

(2, 3)
6
2
int64


In [ ]:

a = np.array([[10,20,30],[4,5,6]])
np.sum(a)      # Sum
np.mean(a)     # Average
np.max(a)      # Maximum
np.min(a)      # Minimum
np.std(a)      # Standard deviation
np.var(a)      # Variance

np.float64(89.91666666666667)

In [ ]:
print("Linspace:", np.linspace(1, 1000, 4))
print("Logspace:", np.logspace(0, 3, 4))

Linspace: [   1.  334.  667. 1000.]
Logspace: [   1.   10.  100. 1000.]


In [ ]:
arr1 = np.array([5,6,7,8,9])
arr2 = np.array([1,2,3,4,5])
print(np.add(arr1,arr2))
print(np.subtract(arr1,arr2))
print(np.multiply(arr1,arr2))
print(np.divide(arr1,arr2))



[ 6  8 10 12 14]
[4 4 4 4 4]
[ 5 12 21 32 45]
[5.         3.         2.33333333 2.         1.8       ]


In [ ]:
#modify_array function
arr = np.array([11,22,33,44,55,66])
arr1 = arr.reshape(2,3)
print(arr1)


[[11 22 33]
 [44 55 66]]


In [ ]:
arr = np.array([1,2,3,4,5,6,7,9])
arr.resize(3,3)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 9 0]]


In [ ]:
arr = np.array([1,2,3,4,5])
print(np.append(arr,7))


[1 2 3 4 5 7]


In [ ]:
arr = np.array([1,2,3,4,5])
print(np.insert(arr,2,8))


[1 2 8 3 4 5]


In [ ]:
arr = np.array([1,2,3,4,5])
print(np.delete(arr,2))


[1 2 4 5]


In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.T)


[[1 4]
 [2 5]
 [3 6]]


In [ ]:
arr = np.array([[1,2,3],[8,4,5]])
print(arr)
print(arr.flatten())



[[1 2 3]
 [8 4 5]]
[1 2 3 8 4 5]


In [ ]:
arr = np.array([1,2,3,4,5,5,4,6,5,4])
arr1 = (np.unique(arr))
print(arr1)


[1 2 3 4 5 6]


In [ ]:
arr = np.array([1,2,3,4,5,5,4,6,5,4])
arr1 = (np.argsort(arr))
print(arr1)


[0 1 2 3 6 9 5 4 8 7]


In [ ]:
#identity function

arr = np.identity(3)
print(arr)

arr = np.diag([1,2,3])
print(arr)

arr = np.array([[1,2,3,],[4,5,6],[6,7,8]])
print (np.diag(arr))



[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]
[1 5 8]


In [ ]:
#rounding function
x = np.array([1,2,3.7,4.1,5.3,5.6])

#round
print(np.round(x))
#floor
print(np.floor(x))
#ceil
print(np.ceil(x))
#trunc
print(np.trunc(x))

[1. 2. 4. 4. 5. 6.]
[1. 2. 3. 4. 5. 5.]
[1. 2. 4. 5. 6. 6.]
[1. 2. 3. 4. 5. 5.]


In [ ]:
#statical_function

arr = np.array([2,3,4,5,6,7])
#mean
print(np.mean(arr))

# median
print(np.median(arr))

#std()
print(np.std(arr))

#  var()
print(np.var(arr))

#  min()
print(np.min(arr))

# max()
print(np.max(arr))

#  argmin()
print(np.argmin(arr))

#  argmax()
print(np.argmax(arr))


# sum()
print(np.sum(arr))

# percentile()
sal = np.array([2008,4500,6600,7000])
print(np.percentile(sal,90))

4.5
4.5
1.707825127659933
2.9166666666666665
2
7
0
5
27
6880.0


In [ ]:
percentile() corrcoef(arr,arr) cov(arr,arr)

In [4]:
# Random function

print(np.random.randint(100, 1000))

np.random.randint(1, 10, size=5)

344


array([8, 6, 7, 2, 9])

In [8]:
np.random.rand(3) #give random number between 0 and 1

np.random.rand(2,3) #2D

array([0.43698597, 0.04785517, 0.6985358 ])

In [9]:
np.random.randn(3) #mean = 0 ,standerd deviation = 1


array([ 0.01752913, -0.58197942, -0.34006204])

In [13]:
arr = [10, 20, 30, 40]
np.random.choice(arr)

np.random.choice(arr, size=3)

array([40, 20, 40])

In [27]:
arr = np.array([1,2,3,4,5])
np.random.shuffle(arr)
print(arr)

[3 4 5 1 2]


In [28]:
np.random.seed(1)
print(np.random.randint(1,10,5))

[6 9 6 1 1]
